const SHARED_STATUS = {
  pending: '#F59E0B',
  assigned: '#3B82F6',
  progress: '#8B5CF6',
  paused: '#EC4899',
  completed: '#10B981',
  cancelled: '#6B7280',
  danger: '#EF4444',
  success: '#10B981',
  warning: '#F59E0B',
  info: '#3B82F6',
};

function hexToRgb(hex) {
  const normalized = hex.replace('#', '');
  const value = normalized.length === 3
    ? normalized.split('').map((char) => char + char).join('')
    : normalized;

  const parsed = Number.parseInt(value, 16);

  return {
    r: (parsed >> 16) & 255,
    g: (parsed >> 8) & 255,
    b: parsed & 255,
  };
}

function withAlpha(hex, alpha) {
  const { r, g, b } = hexToRgb(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function createTheme({
  id,
  label,
  description,
  mode,
  bgPrimary,
  bgSecondary,
  bgTertiary,
  bgElevated,
  cardStart,
  cardEnd,
  accent,
  accentLight,
  accentContrast,
  textPrimary,
  textSecondary,
  textMuted,
  textInverse,
  borderBase,
  neutralBase,
  spotlight,
}) {
  const isDark = mode === 'dark';
  const shadowBase = isDark ? '0, 0, 0' : '15, 23, 42';

  return {
    id,
    label,
    description,
    mode,
    preview: [accent, accentLight, bgPrimary],
    variables: {
      '--page-backdrop': `radial-gradient(circle at top, ${withAlpha(spotlight, isDark ? 0.16 : 0.1)} 0%, transparent 32%), linear-gradient(180deg, ${bgPrimary} 0%, ${bgSecondary} 100%)`,
      '--bg-primary': bgPrimary,
      '--bg-secondary': bgSecondary,
      '--bg-tertiary': bgTertiary,
      '--bg-elevated': bgElevated,
      '--bg-hover': bgElevated,
      '--bg-card': `linear-gradient(145deg, ${cardStart} 0%, ${cardEnd} 100%)`,
      '--bg-card-solid': cardStart,
      '--bg-navbar': withAlpha(bgSecondary, isDark ? 0.82 : 0.9),
      '--bg-sidebar': bgSecondary,
      '--bg-modal': `linear-gradient(145deg, ${cardStart} 0%, ${cardEnd} 100%)`,
      '--bg-input': withAlpha(neutralBase, isDark ? 0.05 : 0.045),
      '--bg-input-focus': withAlpha(accent, isDark ? 0.08 : 0.06),
      '--bg-tab': withAlpha(neutralBase, isDark ? 0.035 : 0.05),
      '--bg-tab-active': withAlpha(neutralBase, isDark ? 0.09 : 0.11),
      '--bg-soft': withAlpha(neutralBase, isDark ? 0.04 : 0.045),
      '--bg-soft-strong': withAlpha(neutralBase, isDark ? 0.07 : 0.08),
      '--bg-soft-hover': withAlpha(neutralBase, isDark ? 0.11 : 0.13),
      '--bg-overlay': isDark ? 'rgba(2, 6, 23, 0.68)' : 'rgba(15, 23, 42, 0.22)',
      '--modal-overlay': isDark ? 'rgba(2, 6, 23, 0.74)' : 'rgba(15, 23, 42, 0.34)',
      '--text-primary': textPrimary,
      '--text-secondary': textSecondary,
      '--text-muted': textMuted,
      '--text-inverse': textInverse,
      '--border': withAlpha(borderBase, isDark ? 0.14 : 0.12),
      '--border-hover': withAlpha(borderBase, isDark ? 0.26 : 0.22),
      '--border-strong': withAlpha(borderBase, isDark ? 0.34 : 0.28),
      '--accent': accent,
      '--accent-light': accentLight,
      '--accent-contrast': accentContrast,
      '--accent-gradient': `linear-gradient(135deg, ${accent} 0%, ${accentLight} 100%)`,
      '--accent-soft': withAlpha(accent, isDark ? 0.14 : 0.11),
      '--accent-soft-hover': withAlpha(accent, isDark ? 0.18 : 0.15),
      '--accent-glow': withAlpha(accent, isDark ? 0.28 : 0.2),
      '--accent-border': withAlpha(accent, isDark ? 0.26 : 0.22),
      '--surface-line': `linear-gradient(90deg, transparent 0%, ${withAlpha(neutralBase, isDark ? 0.1 : 0.12)} 50%, transparent 100%)`,
      '--surface-radial': `radial-gradient(circle at top right, ${withAlpha(accentLight, isDark ? 0.12 : 0.1)}, transparent 60%)`,
      '--sidebar-spotlight': `radial-gradient(ellipse at 30% 0%, ${withAlpha(spotlight, isDark ? 0.14 : 0.12)} 0%, transparent 70%)`,
      '--login-left-glow': `radial-gradient(circle, ${withAlpha(accent, isDark ? 0.12 : 0.1)} 0%, transparent 65%)`,
      '--login-right-glow': `radial-gradient(circle, ${withAlpha(accentLight, isDark ? 0.1 : 0.08)} 0%, transparent 65%)`,
      '--login-panel-spotlight': `radial-gradient(ellipse at 50% 40%, ${withAlpha(accent, isDark ? 0.08 : 0.06)} 0%, transparent 60%)`,
      '--focus-ring': withAlpha(accent, isDark ? 0.24 : 0.18),
      '--scrollbar': withAlpha(neutralBase, isDark ? 0.12 : 0.18),
      '--scrollbar-hover': withAlpha(neutralBase, isDark ? 0.2 : 0.28),
      '--table-row-border': withAlpha(neutralBase, isDark ? 0.04 : 0.08),
      '--table-row-hover': withAlpha(neutralBase, isDark ? 0.03 : 0.055),
      '--nav-active-shadow': `inset 0 0 20px ${withAlpha(accent, isDark ? 0.08 : 0.06)}`,
      '--shadow-sm': `0 2px 10px rgba(${shadowBase}, ${isDark ? 0.28 : 0.12})`,
      '--shadow-md': `0 12px 28px rgba(${shadowBase}, ${isDark ? 0.3 : 0.14})`,
      '--shadow-lg': `0 20px 52px rgba(${shadowBase}, ${isDark ? 0.4 : 0.18})`,
      '--shadow-card': `0 10px 28px rgba(${shadowBase}, ${isDark ? 0.28 : 0.1}), inset 0 1px 0 ${withAlpha(neutralBase, isDark ? 0.04 : 0.18)}`,
      '--shadow-accent': `0 0 32px ${withAlpha(accent, isDark ? 0.18 : 0.12)}`,
      '--status-pending': SHARED_STATUS.pending,
      '--status-assigned': SHARED_STATUS.assigned,
      '--status-progress': SHARED_STATUS.progress,
      '--status-paused': SHARED_STATUS.paused,
      '--status-completed': SHARED_STATUS.completed,
      '--status-cancelled': SHARED_STATUS.cancelled,
      '--danger': SHARED_STATUS.danger,
      '--success': SHARED_STATUS.success,
      '--warning': SHARED_STATUS.warning,
      '--info': SHARED_STATUS.info,
    },
  };
}

export const DEFAULT_THEME_ID = 'minimal-light';
export const THEME_STORAGE_KEY = 'hotel-ops-theme';

export const themes = [
  createTheme({
    id: 'dark-blue',
    label: 'Dark Blue',
    description: 'Deep navy surfaces with crisp sapphire accents.',
    mode: 'dark',
    bgPrimary: '#081120',
    bgSecondary: '#0D1A30',
    bgTertiary: '#132340',
    bgElevated: '#1A2B4B',
    cardStart: '#132340',
    cardEnd: '#0D1A30',
    accent: '#5B8DEF',
    accentLight: '#8CB4FF',
    accentContrast: '#EAF2FF',
    textPrimary: '#F3F7FF',
    textSecondary: '#A5B8D6',
    textMuted: '#64748B',
    textInverse: '#081120',
    borderBase: '#D9E7FF',
    neutralBase: '#FFFFFF',
    spotlight: '#5B8DEF',
  }),
  createTheme({
    id: 'emerald-green',
    label: 'Emerald Green',
    description: 'Cool slate greens with a polished hospitality feel.',
    mode: 'dark',
    bgPrimary: '#071611',
    bgSecondary: '#0E211B',
    bgTertiary: '#133128',
    bgElevated: '#1B3A30',
    cardStart: '#143228',
    cardEnd: '#0E211B',
    accent: '#22C55E',
    accentLight: '#6EE7A0',
    accentContrast: '#E8FFF0',
    textPrimary: '#F2FFF7',
    textSecondary: '#A6D8BB',
    textMuted: '#5F7F70',
    textInverse: '#071611',
    borderBase: '#D9FCE6',
    neutralBase: '#FFFFFF',
    spotlight: '#22C55E',
  }),
  createTheme({
    id: 'purple-neon',
    label: 'Purple Neon',
    description: 'Midnight violets with a sharper futuristic accent.',
    mode: 'dark',
    bgPrimary: '#0D0A1B',
    bgSecondary: '#161029',
    bgTertiary: '#21153B',
    bgElevated: '#2A1E49',
    cardStart: '#22163E',
    cardEnd: '#161029',
    accent: '#B26BFF',
    accentLight: '#E48DFF',
    accentContrast: '#FAF0FF',
    textPrimary: '#FAF5FF',
    textSecondary: '#C8B4E2',
    textMuted: '#786A95',
    textInverse: '#100A1F',
    borderBase: '#F2DAFF',
    neutralBase: '#FFFFFF',
    spotlight: '#B26BFF',
  }),
createTheme({
    id: 'boutique-midnight',
    label: 'Boutique Midnight',
    description: 'Deep charcoal surfaces with elegant brushed gold accents.',
    mode: 'dark',
    bgPrimary: '#0A0A0A',
    bgSecondary: '#141414',
    bgTertiary: '#1A1A1A',
    bgElevated: '#262626',
    cardStart: '#1A1A1A',
    cardEnd: '#141414',
    accent: '#D4AF37',       // Classic Gold
    accentLight: '#F3E5AB',  // Soft Champagne
    accentContrast: '#0A0A0A',
    textPrimary: '#F5F5F5',
    textSecondary: '#A3A3A3',
    textMuted: '#737373',
    textInverse: '#0A0A0A',
    borderBase: '#E5E5E5',
    neutralBase: '#FFFFFF',
    spotlight: '#D4AF37',
  }),
  createTheme({
    id: 'minimal-light',
    label: 'Minimal Light',
    description: 'Bright neutral surfaces with refined slate-blue accents.',
    mode: 'light',
    bgPrimary: '#F5F7FB',
    bgSecondary: '#EDF1F7',
    bgTertiary: '#FFFFFF',
    bgElevated: '#E5EBF4',
    cardStart: '#FFFFFF',
    cardEnd: '#F1F5FB',
    accent: '#2563EB',
    accentLight: '#60A5FA',
    accentContrast: '#EFF6FF',
    textPrimary: '#102033',
    textSecondary: '#4B5E75',
    textMuted: '#718198',
    textInverse: '#F8FBFF',
    borderBase: '#1E293B',
    neutralBase: '#0F172A',
    spotlight: '#60A5FA',
  }),

  createTheme({
    id: 'oled-accessibility',
    label: 'High Contrast (OLED)',
    description: 'Pure black for battery saving with high-visibility cyan accents.',
    mode: 'dark',
    bgPrimary: '#000000',    // Pure Black (turns off OLED pixels)
    bgSecondary: '#000000',
    bgTertiary: '#111111',
    bgElevated: '#1A1A1A',
    cardStart: '#111111',
    cardEnd: '#000000',
    accent: '#06B6D4',       // High-vis Cyan
    accentLight: '#67E8F9',
    accentContrast: '#000000',
    textPrimary: '#FFFFFF',  // Pure White
    textSecondary: '#D4D4D8',
    textMuted: '#A1A1AA',
    textInverse: '#000000',
    borderBase: '#FFFFFF',   // Stronger borders for visibility
    neutralBase: '#FFFFFF',
    spotlight: '#06B6D4',
  }),
];

export const themesById = themes.reduce((collection, theme) => {
  collection[theme.id] = theme;
  return collection;
}, {});
